# Generated by Django 3.0.5 on 2021-10-08 12:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210930_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('measurement_unit', models.CharField(choices=[('г', 'г'), ('стакан', 'стакан'), ('по вкусу', 'по вкусу'), ('ст. л.', 'ст. л.'), ('шт.', 'шт.'), ('мл', 'мл'), ('ч. л.', 'ч. л.'), ('ст. л.', 'ст. л.'), ('капля', 'капля'), ('звездочка', 'звездочка'), ('щепотка', 'щепотка'), ('горсть', 'горсть'), ('кусок', 'кусок'), ('кг', 'кг'), ('пакет', 'пакет'), ('пучок', 'пучок'), ('долька', 'долька'), ('банка', 'банка'), ('упаковка', 'упаковка'), ('зубчик', 'зубчик'), ('стручок', 'стручок'), ('л', 'л'), ('бутылка', 'бутылка'), ('тушка', 'тушка'), ('батон', 'батон'), ('пакетик', 'пакетик'), ('лист', 'лист'), ('стебель', 'стебель'), ('веточка', 'веточка')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='photo')),
                ('text', models.TextField()),
                ('cooking_time', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('color', models.CharField(choices=[('#000000', 'Black'), ('#808080', 'Gray'), ('#C0C0C0', 'Silver'), ('#FFFFFF', 'White'), ('#FF00FF', 'Fuchsia'), ('#800080', 'Purple'), ('#FF0000', 'Red'), ('#FF0000', 'Maroon'), ('#FFFF00', 'Yellow'), ('#808000', 'Olive'), ('#00FF00', 'Lime'), ('#008000', 'Green'), ('#00FFFF', 'Aqua'), ('#008080', 'Teal'), ('#0000FF', 'Blue'), ('#000080', 'Navy')], max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='api.Ingredient')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='api.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredients', through='api.RecipeIngredient', to='api.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='recipe_teg', to='api.Tags'),
        ),
    ]
