# Generated by Django 3.0.5 on 2021-10-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211008_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(null=True, related_name='recipe_ingredients', through='api.RecipeIngredient', to='api.Ingredient'),
        ),
    ]
