# Generated by Django 3.0.5 on 2021-10-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211022_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='recipe_ingredients', through='api.RecipeIngredient', to='api.Ingredient'),
        ),
    ]
