# Generated by Django 3.0.5 on 2021-10-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211022_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredients', through='api.RecipeIngredient', to='api.Ingredient'),
        ),
    ]
