# Generated by Django 3.0.5 on 2021-11-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_favorite_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='recipes',
        ),
        migrations.AddField(
            model_name='favorite',
            name='recipes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to='api.Recipe'),
            preserve_default=False,
        ),
    ]
