# Generated by Django 3.0.5 on 2021-11-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
