# Generated by Django 3.0.5 on 2021-11-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211124_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(choices=[('#000000', 'Черный'), ('#808080', 'Серый'), ('#C0C0C0', 'Серебряный'), ('#FFFFFF', 'Белый'), ('#FF00FF', 'Цвет фуксии (розовый)'), ('#800080', 'Фиолетовый'), ('#FF0000', 'Красный'), ('#800000', 'Бордовый'), ('#FFFF00', 'Желтый'), ('#808000', 'Оливковый'), ('#00FF00', 'Лаймовый'), ('#008000', 'Зеленый'), ('#00FFFF', 'Цвет морской волны'), ('#008080', 'Бирюзовый'), ('#0000FF', 'Синий'), ('#000080', 'Темно-синий')], max_length=500),
        ),
    ]
