# Generated by Django 3.0.5 on 2021-11-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211129_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
