# Generated by Django 3.0.5 on 2021-11-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20211129_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'г'), ('стакан', 'стакан'), ('по вкусу', 'по вкусу'), ('ст. л.', 'ст. л.'), ('шт.', 'шт.'), ('мл', 'мл'), ('ч. л.', 'ч. л.'), ('ст. л.', 'ст. л.'), ('капля', 'капля'), ('звездочка', 'звездочка'), ('щепотка', 'щепотка'), ('горсть', 'горсть'), ('кусок', 'кусок'), ('кг', 'кг'), ('пакет', 'пакет'), ('пучок', 'пучок'), ('долька', 'долька'), ('банка', 'банка'), ('упаковка', 'упаковка'), ('зубчик', 'зубчик'), ('стручок', 'стручок'), ('л', 'л'), ('бутылка', 'бутылка'), ('тушка', 'тушка'), ('батон', 'батон'), ('пакетик', 'пакетик'), ('лист', 'лист'), ('стебель', 'стебель'), ('веточка', 'веточка')], max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название ингредиениа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(max_length=150, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(max_length=150, unique=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=150, unique=True, verbose_name='Никнейм'),
        ),
    ]
