# Generated by Django 3.0.5 on 2021-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20211129_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#000000', 'Черный'), ('#808080', 'Серый'), ('#C0C0C0', 'Серебряный'), ('#FFFFFF', 'Белый'), ('#FF00FF', 'Цвет фуксии (розовый)'), ('#800080', 'Фиолетовый'), ('#FF0000', 'Красный'), ('#800000', 'Бордовый'), ('#FFFF00', 'Желтый'), ('#808000', 'Оливковый'), ('#00FF00', 'Лаймовый'), ('#008000', 'Зеленый'), ('#00FFFF', 'Цвет морской волны'), ('#008080', 'Бирюзовый'), ('#0000FF', 'Синий'), ('#000080', 'Темно-синий')], max_length=500, verbose_name='Цвет тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг тега'),
        ),
    ]
