# Generated by Django 3.0.5 on 2021-12-02 16:10

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20211130_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[api.validators.CustomMinValidator(1)], verbose_name='Количество ингредиента промежуточной модели'),
        ),
    ]
